http:
  port: 443
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  auth:
    host: localhost
    paths: ['/auth','/auth/*']
  qrcode:
    host: localhost
    paths: ['/qrcode','/qrcode/*']
  admin:
    host: localhost
    path: ['/admin', '/admin/*']
  front:
    host: localhost
    path: ['/frontService', '/frontService/*']
  crud:
    host: localhost
    path: ['/crud', '/crud/*']
  entrance:
    host: localhost
    path: ['/webhook', '/webhook/*', '/payment', '/payment/*']
  
serviceEndpoints:
  httpbin:
    url: 'https://api-semfila.api-semfila.online'
  authService:
    url: 'http://localhost:5000'
  qrcodeService:
    url: 'http://localhost:6000'
  adminService:
    url: 'http://localhost:3000'
  frontService:
    url: 'http://localhost:4000'
  crudService:
    url: 'http://localhost:7000'
  entranceService:
    url: 'http://locahost:8000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  authPipeline:
    apiEndpoints:
      - auth
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
  qrcodePipeline:
    apiEndpoints:
      - qrcode
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: qrcodeService
              changeOrigin: true
  adminPipeline:
    apiEndpoints:
      - admin
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: adminService
              changeOrigin: true
  frontPipeline:
    apiEndpoints:
      - front
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: frontService
              changeOrigin: true
  crudPipeline:
    apiEndpoints:
      - crud
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: crudService
              changeOrigin: true
  entrancePipeline:
    apiEndpoints:
      - entrance
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: entranceService
              changeOrigin: true